# Generated by Django 3.0.3 on 2020-03-12 16:25

import core.models
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('cargo', models.CharField(max_length=50, verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('icone', models.CharField(choices=[('lnr lnr-rocket', 'Foguete'), ('lnr lnr-laptop-phone', 'Laptop'), ('lnr lnr-layers', 'Layer'), ('lnr lnr-cog', 'Cog'), ('lnr lnr-magnifier', 'Lupa'), ('lnr lnr-pencil', 'lápis')], default='', max_length=100, verbose_name='Icone')),
                ('texto', models.TextField(default='', max_length=500, verbose_name='Texto')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
            },
        ),
        migrations.CreateModel(
            name='Publicacoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('sub_title', models.CharField(max_length=500, verbose_name='Subtitulo')),
                ('Imagem', stdimage.models.StdImageField(upload_to=core.models.get_file_path)),
                ('text', models.TextField(max_length=4000, verbose_name='Texto')),
            ],
            options={
                'verbose_name': 'Publicação',
                'verbose_name_plural': 'Publicações',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('imagem', stdimage.models.StdImageField(upload_to=core.models.get_file_path, verbose_name='Imagem')),
                ('facebook_icon', models.CharField(choices=[('fa fa-facebook', 'Facebook'), ('fa fa-twitter', 'Twitter'), ('fa fa-linkedin', 'Linkedin'), ('fa fa-instagram', 'Instagram')], default='', max_length=50, verbose_name='Facebook')),
                ('twitter_icone', models.CharField(choices=[('fa fa-facebook', 'Facebook'), ('fa fa-twitter', 'Twitter'), ('fa fa-linkedin', 'Linkedin'), ('fa fa-instagram', 'Instagram')], default='', max_length=50, verbose_name='Twitter')),
                ('linkedin_icone', models.CharField(choices=[('fa fa-facebook', 'Facebook'), ('fa fa-twitter', 'Twitter'), ('fa fa-linkedin', 'Linkedin'), ('fa fa-instagram', 'Instagram')], default='', max_length=50, verbose_name='Linkedin')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cargo', verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
            },
        ),
    ]
