# Generated by Django 3.0.3 on 2020-03-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('icon', models.CharField(choices=[('lnr lnr-pencil', 'Lápis'), ('lnr lnr-code', 'html'), ('lnr lnr-mustache', 'Emote: Bigode'), ('lnr lnr-chart-bars', 'Gráfico'), ('lnr lnr-tablet', 'Tablete'), ('lnr lnr-earth', 'Planeta Terra'), ('lnr lnr-hourglass', 'Ampulheta(Relógio de areia)'), ('lnr lnr-rocket', 'Foguete'), ('lnr lnr-screen', 'Monitor')], max_length=50, verbose_name='Icone')),
                ('description', models.CharField(max_length=50, verbose_name='Descrição')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
