# Generated by Django 3.0.3 on 2020-03-14 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_services'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='features',
            options={'verbose_name': 'Especialidade', 'verbose_name_plural': 'Especialidades'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'Serviço', 'verbose_name_plural': 'Serviços'},
        ),
    ]
