# Generated by Django 3.0.3 on 2020-03-17 22:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200314_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacoes',
            name='sub_title',
            field=models.CharField(max_length=500, verbose_name='Resumo'),
        ),
        migrations.AlterField(
            model_name='publicacoes',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
