# Generated by Django 3.0.3 on 2020-03-17 23:00

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200317_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacoes',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
