# Generated by Django 3.0.3 on 2020-03-18 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_contato'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contato',
            options={'verbose_name': 'Mensagem', 'verbose_name_plural': 'Mensagens'},
        ),
    ]
