# Generated by Django 3.0.3 on 2020-03-18 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200318_0326'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contato',
        ),
    ]
