# Generated by Django 3.0.3 on 2020-03-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_contato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='facebook_icon',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='linkedin_icone',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='twitter_icone',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='social_icon_1',
            field=models.CharField(choices=[('fa fa-facebook', 'Facebook'), ('fa fa-twitter', 'Twitter'), ('fa fa-linkedin', 'Linkedin'), ('fa fa-instagram', 'Instagram'), ('fa fa-whatsapp', 'Whatsapp')], default='', max_length=50, verbose_name='Icone 1'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='social_icon_2',
            field=models.CharField(choices=[('fa fa-facebook', 'Facebook'), ('fa fa-twitter', 'Twitter'), ('fa fa-linkedin', 'Linkedin'), ('fa fa-instagram', 'Instagram'), ('fa fa-whatsapp', 'Whatsapp')], default='', max_length=50, verbose_name='Icone 2'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='social_icon_3',
            field=models.CharField(choices=[('fa fa-facebook', 'Facebook'), ('fa fa-twitter', 'Twitter'), ('fa fa-linkedin', 'Linkedin'), ('fa fa-instagram', 'Instagram'), ('fa fa-whatsapp', 'Whatsapp')], default='', max_length=50, verbose_name='Icone 3'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='social_link_1',
            field=models.CharField(default='', max_length=200, verbose_name='Link 1'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='social_link_2',
            field=models.CharField(default='', max_length=200, verbose_name='Link 2'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='social_link_3',
            field=models.CharField(default='', max_length=200, verbose_name='Link 3'),
        ),
    ]
