# Generated by Django 3.0.3 on 2020-03-19 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_clientes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('icon', models.CharField(choices=[('lnr lnr-briefcase', 'Maleta'), ('lnr lnr-coffee-cup', 'Café'), ('lnr lnr-users', 'Usuarios'), ('lnr lnr-clock', 'Relógio'), ('lnr lnr-heart', 'Coração'), ('lnr lnr-chart-bars', 'Gráfico'), ('lnr lnr-tablet', 'Tablet'), ('lnr lnr-earth', 'Planeta Terra'), ('lnr lnr-hourglass', 'Ampulheta(Relógio de areia)'), ('lnr lnr-rocket', 'Foguete'), ('lnr lnr-screen', 'Monitor')], max_length=50, verbose_name='Icone')),
                ('text', models.CharField(max_length=80, verbose_name='Título')),
            ],
            options={
                'verbose_name': 'Contador',
            },
        ),
        migrations.AlterField(
            model_name='services',
            name='icon',
            field=models.CharField(choices=[('lnr lnr-pencil', 'Lápis'), ('lnr lnr-code', 'html'), ('lnr lnr-mustache', 'Emote: Bigode'), ('lnr lnr-chart-bars', 'Gráfico'), ('lnr lnr-tablet', 'Tablet'), ('lnr lnr-earth', 'Planeta Terra'), ('lnr lnr-hourglass', 'Ampulheta(Relógio de areia)'), ('lnr lnr-rocket', 'Foguete'), ('lnr lnr-screen', 'Monitor')], max_length=50, verbose_name='Icone'),
        ),
    ]
