# Generated by Django 3.0.3 on 2020-03-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200319_1746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counter',
            options={'verbose_name': 'Contador', 'verbose_name_plural': 'Contadores'},
        ),
        migrations.AddField(
            model_name='counter',
            name='number',
            field=models.IntegerField(default=0, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='services',
            name='icon',
            field=models.CharField(choices=[('lnr lnr-pencil', 'Lápis'), ('lnr lnr-code', 'html'), ('lnr lnr-mustache', 'Emote: Bigode'), ('lnr lnr-chart-bars', 'Gráfico'), ('lnr lnr-tablet', 'Tablet'), ('lnr lnr-earth', 'Planeta Terra'), ('lnr lnr-hourglass', 'Ampulheta(Relógio de areia)'), ('lnr lnr-rocket', 'Foguete'), ('lnr lnr-screen', 'Monitor'), ('lnr lnr-laptop-phone', 'Laptop')], max_length=50, verbose_name='Icone'),
        ),
    ]
