# Generated by Django 3.0.3 on 2020-05-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200320_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='icone',
            field=models.CharField(choices=[('lnr lnr-rocket', 'Foguete'), ('lnr lnr-laptop-phone', 'Laptop'), ('lnr lnr-layers', 'Layer'), ('lnr lnr-cog', 'Cog'), ('lnr lnr-magnifier', 'Lupa'), ('lnr lnr-pencil', 'lápis'), ('lnr lnr-code', 'html'), ('lnr lnr-chart-bars', 'Gráfico'), ('lnr lnr-tablet', 'Tablet'), ('lnr lnr-earth', 'Planeta Terra'), ('lnr lnr-hourglass', 'Ampulheta(Relógio de areia)'), ('lnr lnr-screen', 'Monitor'), ('lnr lnr-envelope', 'E-mail'), ('lnr lnr-film-play', 'Video'), ('lnr lnr-picture', 'Imagem'), ('lnr lnr-store', 'Loja'), ('lnr lnr-pie-chart', 'Gráfico circular'), ('lnr lnr-smartphone', 'Celular'), ('lnr lnr-cart', 'Carrinho de Supermercado'), ('lnr lnr-camera-video', 'Camera de video'), ('lnr lnr-bullhorn', 'Megafone'), ('lnr lnr-thumbs-up', 'Positivo(joia)')], default='', max_length=100, verbose_name='Icone'),
        ),
        migrations.AlterField(
            model_name='services',
            name='icon',
            field=models.CharField(choices=[('lnr lnr-pencil', 'Lápis'), ('lnr lnr-code', 'html'), ('lnr lnr-mustache', 'Emote: Bigode'), ('lnr lnr-chart-bars', 'Gráfico'), ('lnr lnr-tablet', 'Tablet'), ('lnr lnr-earth', 'Planeta Terra'), ('lnr lnr-hourglass', 'Ampulheta(Relógio de areia)'), ('lnr lnr-rocket', 'Foguete'), ('lnr lnr-screen', 'Monitor'), ('lnr lnr-laptop-phone', 'Laptop')], max_length=50, verbose_name='Icone'),
        ),
    ]
